name: Run Python Script

on:
  push:
    branches: [ main ]  # Adjust branch as needed

jobs:
  run_script:
    runs-on: ubuntu-latest  # Choose the OS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify Python version

    - name: Run Python script
      run: python path/to/your_script.py  # Replace with your script's path
